# Paths
export PATH="$HOME/bin:$PATH"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# History
export HISTFILE="${XDG_STATE_HOME}/zsh/history"
HISTSIZE=10000
SAVEHIST=10000
mkdir -p "$(dirname "$HISTFILE")"
setopt append_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks

# Colors
autoload -Uz colors && colors
setopt prompt_subst

# Enter the folder without writing cd
setopt AUTO_CD

# Aliases
alias ll='ls -lah'
alias la='ls -A'
alias gs='git status'
alias gp='git push'
alias gd='git diff'
alias update="bash $HOME/Documents/bashscripts/arch-install-packages.sh"

# Keybindings
bindkey '^R' history-incremental-search-backward
bindkey '^[[3~' delete-char

# Completion
autoload -Uz compinit
compinit

# Neovim as default editor
export EDITOR=nvim

# Prompt
git_info() {
  local branch=$(git symbolic-ref --short HEAD 2>/dev/null)
  [[ -z $branch ]] && return
  local dirty=""
  [[ -n $(git status --porcelain 2>/dev/null) ]] && dirty="*"
  echo "%F{150}(${branch}${dirty})%f"
}
precmd() { print -Pn "\e]0;%~\a" }
PROMPT='%F{014}%n%f %F{110}%~%f $(git_info) %F{111}›%f '

# Plugins (zplug)
if [ ! -d ~/.zplug ]; then
  git clone https://github.com/zplug/zplug ~/.zplug
fi
source ~/.zplug/init.zsh
zplug "zsh-users/zsh-syntax-highlighting"
zplug load

# XDG Paths
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export PUB_CACHE="${XDG_CACHE_HOME}/pub-cache"
export FLUTTER_ROOT="${XDG_DATA_HOME}/flutter"
export __GL_SHADER_DISK_CACHE_PATH="${XDG_CACHE_HOME}/nvidia"
export CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nvidia"
export GOPATH="${XDG_DATA_HOME}/go"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node_repl_history"
